# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghost" do
  version "1.0.0-beta.3"

  on_macos do
    on_arm do
      sha256 "4f53c668f6fbdfc47d4ca9d1a4887ae8d9585767b8de619941d287d060aac401"
      url "https://github.com/ghost-language/ghost/releases/download/v#{version}/ghost_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a44edc33ed19f7c56bdb532f322357239f23f4c2463e1f1ad4a4be92a989c518"
      url "https://github.com/ghost-language/ghost/releases/download/v#{version}/ghost_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6c20ca65e4712a778c3ccd76d12fff94097579f9e7cf05e9c54e79dcbc15e9e5"
      url "https://github.com/ghost-language/ghost/releases/download/v#{version}/ghost_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5aedb6b40aff677aa36f31223343fa87e4cdbdb453c0fd35ca61e06b999bfd1a"
      url "https://github.com/ghost-language/ghost/releases/download/v#{version}/ghost_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ghost"
  desc "Ghost, a dynamically typed scripting language."
  homepage "https://github.com/ghost-language/ghost"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghost"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghost"]
    end
  end

  # No zap stanza required
end
