# This file is generated by Lumen's release workflow. DO NOT EDIT.
cask "lumen" do
  arch arm: "arm64", intel: "amd64"

  version "0.2.1"
  sha256 arm:   "232929613b004bcfa6c3fdf72d545e7ecab80d87aa28bb0b3970338c2ad7870f",
         intel: "5039a5f8cb6c26b78af8d6e85a00d748c5b5643c79f14bab4dd28017c7cc8f47"

  url "https://github.com/ghost-language/lumen/releases/download/v#{version}/lumen_v#{version}_darwin-#{arch}.tar.gz"
  name "Lumen"
  desc "Lightweight 2D game engine for Ghost"
  homepage "https://github.com/ghost-language/lumen"

  # The archive holds a folder, not a bare binary: SDL2 is linked
  # dynamically and its libraries travel beside the executable, with
  # their install names rewritten to @executable_path/libs. Only the
  # executable is linked onto PATH; the libraries stay next to it.
  binary "lumen_v#{version}_darwin-#{arch}/lumen"

  # The binaries are ad-hoc signed but not notarised, so macOS
  # quarantines them on download and refuses the first run. The whole
  # staged folder is cleared, not just the executable - a quarantined
  # dylib is refused just as firmly as a quarantined binary.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path]
  end
end
